### ISSUE TITLE
Certain Wolfram Alpha Queries Failing (bin/wa script)

### ISSUE THREAD

**Issue by gregdotca** [dmi3/bin#1]
I'm trying to use your Wolfram Alpha CLI script (bin/wa), but for some reason it just doesn't want to work on certain queries. It seems to be an issue with queries that are trying to return images.

This works fine:

```
# wa 30 days from today
Wednesday, January 29, 2020
```

But this fails:

```
# wa 100 usd to cad
No short answer available, downloading full answer...
display-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.
```

I have ImageMagick installed and am using the VIEWER="display" option in the wa script.

Any idea what might be going on here?

**Comment by dmi3** [comment]
If set `VIEWER="cat"` response will be `Wolfram|Alpha did not understand your input`. This is inconsistent for `api.wolframalpha.com/v1/result` and `api.wolframalpha.com/v1/simple` endpoints.

Other currencies show wrong result:

```
➤ wa 10 pounds to eur
10 euros                                                       
➤ wa 10 kronas to eur
10 euros 
``` 

As such type of queries were definitely working during last year (checked my shell history) this looks like a temporary issue with Wolfram Alpha Exchange API.

I suggest we wait and see if this is resolved on Wolfram Alpha API. If inconsistency persists, I will send bug report to Wolfram Alpha.

**Comment by gregdotca** [comment]
It seems as though this was either fixed, or it's an intermittent issue. The USD to CAD conversion is now working.

```
# wa 100 usd to cad
about 130.72 Canadian dollars
```

Thanks for the WA script, it's super helpful! I regularly use WA for various lookups and your script just makes it that much easier and faster.

**Comment by dmi3** [comment]
Seems to be fixed on Wolfram|Alpha side
